# Generated by Django 4.2.7 on 2023-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=255, verbose_name='loc')),
                ('cases', models.IntegerField(verbose_name='cases')),
                ('deaths', models.IntegerField(verbose_name='deaths')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('Region', models.CharField(max_length=255, verbose_name='Region')),
            ],
        ),
    ]
